site_name: Epoch Notes
site_description: Explore deep learning, machine learning, and MLOps through personal projects, tutorials, and insights. Join me as I dive into the world of AI and share my journey.
site_url: https://NeuralNoble.github.io
site_author: Aman Anand
repo_url: https://github.com/NeuralNoble/NeuralNoble.github.io
repo_name: NeuralNoble/NeuralNoble.github.io

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.action.edit
    - content.action.view
    - navigation.sections
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - search.share
    - toc.follow
    - content.math



  font:
    text: Inter
    code: JetBrains Mono



markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format
            kwds: { which: generic }
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tilde
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
#  - toc:
#      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format
            kwds: { which: generic }
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg




extra:
  social:
      - icon: fontawesome/brands/x-twitter
        link: https://x.com/NeuralWarlock
        name: Follow on X
      - icon: fontawesome/brands/github
        link: https://github.com/NeuralNoble
        name: See my GitHub Profile
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/aman-anand-10b51320b/
        name: Connect on LinkedIn
      - icon: material/email
        link: mailto:amananand1618@gmail.com
        name: E-Mail
  #    - icon: material/account-box
  #      link:
  #      name: Resume as PDF

copyright: |
  Copyright &copy; 2025 <a href="https://github.com/NeuralNoble">Aman Anand</a>




# Plugins
plugins:
  - blog:
        path: blog/posts
        archive_date_format: yyyy
        archive_url_date_format: yyyy/MM
        generate_archive: true
        post_url_format: "{slug}"
  - search:
  - social:
  - minify:
      minify_html: true

  - macros:
      include_yaml:
        - about: docs/render_yaml/about.yaml


  - glightbox:
      touchNavigation: false
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true         # <-- add this line


hooks:
  - hooks/socialmedia.py
  - hooks/generate_simpleicons_css.py
  - hooks/prettify_simpleicons_json.py


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

extra_css:
  - stylesheets/custom.css
  - stylesheets/extra.css
  - stylesheets/simpleicons.css


nav:
  - Home: index.md
  - Blog:
      - blog/index.md
      - blog/posts/GELU.md
      - blog/posts/Activation-functions.md


  - Experiments:
      - experiments/index.md
  - Notes:
      - notes/index.md
  - Projects:
      - Projects/index.md
  - About: about/index.md
