authors:
  Aman:
    name: Aman Anand
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/156664113?v=4
    url: https://github.com/NeuralNoble


  chatgpt:
    name: ChatGPT
    description: Bot
    avatar: https://cdn-icons-png.flaticon.com/512/12222/12222560.png
    url: https://chat.openai.com